import {ReactElement, ReactNode} from "react";
import Head from "next/head";
import Script from "next/script";

export default function Layout({children}: { children: ReactNode }): ReactElement {
    return (
        <>
            <Head>
                <title>Event</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            {children}

            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
                    crossOrigin="anonymous"></Script>
        </>
    );
}
